version: '3.8'

services:
  # Development database (SQLite)
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///iot_security_dev.db
      - SECRET_KEY=dev-secret-key
      - JWT_SECRET_KEY=dev-jwt-secret-key
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./uploads:/app/uploads
      - ./data:/app/data
    command: flask run --host=0.0.0.0 --port=5000 --reload
    restart: unless-stopped

  # Redis for development
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

volumes:
  redis_dev_data:
